### ISSUE TITLE
Per-collider mass-properties

### ISSUE THREAD

**Issue by emilk** [dimforge/rapier#132]
Currently the mass properties of a collider is computed from its shape and density. For some shapes, such as `TriMesh`, this is always zero.

I'd like to be able to (optionally) specify the `MassProperties` per `ColliderBuilder`. This will make it easy to override or specify it per collider, and still have rapier compute the final `MassProperties` of the `RigidBody` automatically.

# Proposal
**EDIT**: the source is easier to read: https://github.com/dimforge/rapier/pull/133

I propose we add `mass_properties: MassProperties` member to `Collider`. It (like all other members) will be set at initialization and never changed.

To `ColliderBuilder` we add a `mass_properties: Option<MassProperties>` member and a function to set it. In `ColliderBuilder::build` we check if `mass_properties` is set, and if so assign it to `Collider::mass_properties` (and also use it to compute the average `density` so we don't have to remove the `Collider::density()` member). If `ColliderBuilder::mass_properties` is not set, we compute the `mass_properties` from `Shape::mass_properties` and `ColliderBuilder::get_density`

**Comment by sebcrozet** [comment]
Hi! Thank you for this proposal. This is a great idea from a user-experience point of view, but I'm not sure this is the best approach considering the potential memory overhead this implies. In particular, I feel like setting the mass properties explicitly is something most users won't do, which makes the memory overhead less justifiable.

Right now, you can use `RigidBodyBuilder::mass_properties` to set the initial mass properties of a rigid-body (I say "initial" because the collider's mass properties will be added to that afterwards). So the typical way of having full control over the mass-properties of a rigid-body right now is to set it with `RigidBodyBuilder::mass_properties` and use 0 for the density of the colliders attached to it.

Here are some though on how we could avoid this memory overhead:
- Instead of modifying colliders, we could just make it easier to compose two `MassProperties`, and add a new `MassProperties` contribution to an existing `RigidBody`. That way the user just has to call ` shape.mass_properties()` to get the properties of a shape, and use the improve rigid-body API to take that contribution into account.
- Or we could modify the `ColliderBuilder` only, so it contains a `MassProperties` field. And that field would be taken into account by `ColliderSet::insert` to update the mass-properties of its parent rigid-body. But the collider itself never contains that `MassProperties` field.
- Or we could add an `Option<Box<MassProperties>>` field to colliders. That way it won't consume any significant memory in the most common case where the user just relies on the collider density instead of setting the mass-properties explicitly.

The only case where I believe making `MassProperties` part of the collider directly would be necessary is if the user wants their custom mass-properties to be properly removed from the rigid-body when the collider is removed from the `ColliderSet`. Though I am not sure this is something people do often in games (delete one collider instead of deleting the whole rigid-body)?

**Comment by emilk** [comment]
I think you are making good points. Making it easier to change the mass props of a rigid body is certainly a good thing in its own right, regardless of other paths.

I like the second suggestion, but `ColliderSet::insert` currently takes a `Collider`, not a `ColliderBuilder`.

Adding/removing colliders at runtime is a slim use-case that I think can just as well be accomplished with creating a new rigid body instead of reusing the existing one.

**Comment by sebcrozet** [comment]
> I like the second suggestion, but ColliderSet::insert currently takes a Collider, not a ColliderBuilder.

Ah, you're right. So I guess the second suggestion can't be done without making the insertion method generic (so it takes a `Into<Collider>` instead of a `Collider`). After giving it more thought one downside of doing the second suggestion is that people may end up confused by thinking that the `ColliderBuilder::mass_properties` attaches the mass-properties to the collider (which it does not).

Maybe the non-ambiguous alternative is to add a method like this to the `RigidBody`:
```rust
impl RigidBody {
    pub fn add_mass_properties(&mut self, props: MassProperties, props_frame: &Isometry<Real>, wake_up: bool) {
        // TODO: change `add_collider` so it  calls this method.
        let mass_properties = self.mass_properties + props.transform_by(props_frame);
        self.set_mass_properties(mass_properties, wake_up);
    }
}
```

**Comment by emilk** [comment]
I think the `Option<Box<MassProperties>>` idea is really attractive, as that is the (as far as I can see) only ergonomic way to support removing colliders from bodies. For instance, moving a collider from one body to another (re-parenting) is something that ideally should be as easy as removing a collider and adding it again with a new parent, but with the current design that requires the user to do their own book-keeping for any non-trivial shape (meshes or other shapes with custom mass properties)
