### ISSUE TITLE
applyForce doesn't work at all, rigid body doesn't move

### ISSUE THREAD

**Issue by abnud1** [dimforge/rapier#19]
I'm using the JS Bindings of this library and I'm trying to move a rigid body inside the world by applying a force to it.

For some reason `rigidBody.applyForce(new RAPIER.Vector(10,0,0),true)` should move the rigidBody along x axis but it doesn't.

I'm calling applyForce inside my game loop so definitely a continuous force, I tried waking up the rigidBody manually, I'm applying the force before `world.step`, should it come after `world.step` ? I don't think so.

oh `rigidBody.setTranslation` works but I don't want that since I want to apply force on mouse move so there is a condition here and when that condition is false aka when mouse stops moving the rigidBody returns to its initial position, I'm not sure why

Is this expected behaviour ? what should I do in my case then ?

**Comment by sebcrozet** [comment]
Hi! Can you provide some details on how you initialize your rigid-body? Is is a dynamic body? Does it have any collider attached to it?

**Comment by abnud1** [comment]
@sebcrozet here is the initialization code
```js
world = new rapier.World(0, 0, -9.81);
const tableDesc = new rapier.RigidBodyDesc("static");
tableDesc.setTranslation(50, 0, 0);
table = world.createRigidBody(tableDesc);
let tableCollider = rapier.ColliderDesc.cuboid(75, 50, 1);
table.createCollider(tableCollider);
const paperDesc = new rapier.RigidBodyDesc("dynamic");
paperDesc.setTranslation(15, 0, 10);
paper = world.createRigidBody(paperDesc);
let paperCollider = rapier.ColliderDesc.cuboid(10, 10, 1);
paperCollider.density = 2;
paper.createCollider(paperCollider);
```

**Comment by sebcrozet** [comment]
@abnud1 Thanks! Did you try with a significantly stronger force (say with magnitude 1000 or perhaps higher)? Assuming SI units, our `paper` is very big (20 meters × 20 meters × 2 meters) and heavy (`(20 * 20 * 2 * 2) = 1600` Killograms), my guess is that the force you are applying is not strong enough to overcome friction forces originating from the contact between the paper and the table.

**Comment by abnud1** [comment]
@sebcrozet trying a strong force worked, the length units are actually in cm, I didn't realize that mass is computed with equation `width * height * zheight * density`, is it mandatory to use meters ?

**Comment by sebcrozet** [comment]
Yes, the mass is obtained from the volume multiplied by the density.
Using meters is not mandatory. They are just recommended because they tend to avoid too large values (that would result in numerical instabilities) for average life-sized simulations. 

You can use centimeters if you want. But in that case you need to keep all your units coherent. In particular, this means you assume density is expressed in `kg/cm³` units instead of `kg/m³`as usual. The [average density of paper](https://www.aqua-calc.com/page/density-table/substance/paper-coma-and-blank-standard) seems to be about 1200kg/m³ which is equal to 0.0012kg/cm³

So assuming you meat to use 2000kg/m³ for your paper's density, you should set `paperCollider.density = 0.0012` to keep your choice of units coherent.

**Comment by abnud1** [comment]
@sebcrozet thank you so much and have a nice day
