### ISSUE TITLE
Support rounded corners in cuboid colliders

### ISSUE THREAD

**Issue by stephanemagnenat** [dimforge/rapier#29]
Unity colliders support small [rounded corners](https://docs.unity3d.com/ScriptReference/BoxCollider2D-edgeRadius.html), which Box2D/Planck-JS do not support, and that are important when making 2-D games when a character moves over several platforms. Without that, numerical errors might spuriously block the character even if platforms are at the same altitude. If the platforms are static, they can be pre-processed into a single shape, but if platforms are moving, they cannot, yet in some configuration they can touch and the character should be able to move smoothly from one to another. The edge radius of Unity box colliders solves that.

As far as I can see, currently Rapier's cuboid colliders do not support that. It would be nice to support that.

**Comment by sebcrozet** [comment]
Characters are often represented by capsules so they should not suffer from this problem too much.
But yeah, adding rounded corners would be nice. This is something that can be handled for free for arbitrary convex polyhedron (because they already require a generic algorithm that supports rounded corners out-of-the-box). For simple shapes like triangles, and cuboids, we may need some extra work to make it efficient.

**Comment by sebcrozet** [comment]
Rapier will support rounded corners for all convex shapes (including cuboid) in its next version, scheduled to be released at the end of January 2021.
