### ISSUE TITLE
Removing a collided body doesn't trigger an event

### ISSUE THREAD

**Issue by jcornaz** [dimforge/rapier#299]
Hi, 

If I remove a rigid body `A` that is collided with a rigid body `B`, I would expect the next step to trigger a `ContactEvent::Stopped`, because the collision state of the rigid body `B` has changed from collided to not collided.

But it looks like that is not the case and no event is triggered when we remove a collided rigid body. Is that intentional?

**Comment by sebcrozet** [comment]
Hi! Yes this is intentional. As soon as a rigid-body/collider is removed, it no longer exists from the point of view of the physics engine. Therefore no event is generated.

**Comment by jcornaz** [comment]
Ok, thanks for the precision. 

That's a bit unfortunate and not very intuitive to me. Of course, the body no longer exists, but precisely it means the collision also ended because it is not possible that the object continues to collide with something that no longer exists. 

If we imagine being an observer and only seeing the events, we would see a collision starting but never see it ended, even if the collision has obviously ended in that case.

Is there a chance that we can improve it?

**Comment by sebcrozet** [comment]
Yeah, this is open to discussion. The benefit for not generating events for deleted colliders are:
1. The user has the guarantee that the handles given to the events are valid.
2. The collider removal code is simpler.
3. These additional events could cause some ABA problems for our JS bindings which don’t support generational indices.

Regarding 1, it is perhaps best to let the user checks that the removed collider is still valid, instead of simply skipping the events. This is a soft guarantee anyway since the user may very well delete colliders after a `.step` but before they  start reading the events.

The point 3 should be fixable without too much difficulties.

**Comment by jcornaz** [comment]
The point 1 is not so important to me. No matter what, to access the body we need to ask for a reference from `RigidBodySet` which returns an `Option` forcing the user code to handle the case of the deleted body.

The point 2 is more of a development/maintenance cost. Of course very important and must be considered. But a user of the library is not really concerned by how complex the implementation is.

The point 3 sounds like the most problematic to me. I didn't know that the JS bindings were not supporting generational indices. But it's great if you think it can be solved without too much difficulty.
