### ISSUE TITLE
Use glam in public API?

### ISSUE THREAD

**Issue by SUPERCILEX** [dimforge/rapier#317]
I just started using this with Bevy and found it very odd to be converting between glam and nalgebra. Not sure if this is possible.

**Comment by sebcrozet** [comment]
Since `rapier` is written with `nalgebra`, it wouldn’t make much sense to use `glam` in public API (especially since some elements, like heightfields or multibodies require `DVector/DMatrix` which have no equivalent in `glam`).

For a `glam` based interaction with `Bevy`, please check out the [bevy_rapier2d](https://crates.io/crates/bevy_rapier2d) or [bevy_rapier3d](https://crates.io/crates/bevy_rapier3d) crate.
