### ISSUE TITLE
Feature Request: Non uniform linear damping

### ISSUE THREAD

**Issue by nwpointer** [dimforge/rapier#368]
Other engines I've used allow the passing of a vector3 when adjusting linear damping.

Comes in handy for limiting the speed of a say a character controller in the x-y direction but allowing it to move normally along the z axis.

Interested to see if anybody else would find this useful.

**Comment by sebcrozet** [comment]
Hi! Damping will slow down a rigid-body but won’t actually limit its speed. In order to actually limit the speed of a rigid-body, you can cap it manually.

Most physics engine I am aware of (PhysX, Bullet, Box2D) don’t support separate damping coefficient along each coordinate axes, and I’m not sure the feature would be generally useful enough to justify the extra 2 floats on all the rigid-bodies. So I am also interested to see other examples of use-cases to see if it’s worth it.

**Comment by nwpointer** [comment]
Thanks for the info!

Regarding other engines I was looking at cannon.js and bullet but confusing linearFactor with linearDampening. So seems like you're right, most don't seem to support vec3 damping.

Can't think of any other usecases and think I figured out how to implement what I wanted to do in my app code so agree its probably not worth it if supporting if it would increase the memory footprint of every object.
