### ISSUE TITLE
Where could I get the Demo code?

### ISSUE THREAD

**Issue by CodingYiyi** [dimforge/rapier#405]
https://rapier.rs/demos3d/index.html

I noticed this website as a Demo, I wonder if I can reach this code for local debug.

**Comment by sebcrozet** [comment]
Hi! The code for the demos are there: [2D](https://github.com/dimforge/rapier.js/tree/master/testbed2d/src/demos) and [3D](https://github.com/dimforge/rapier.js/tree/master/testbed3d/src/demos). Though keep in mind that these are based on the Typescript bindings for Rapier.

If you are working with Rust, you can take a look at the examples directories: [2D](https://github.com/dimforge/rapier/tree/master/examples2d) and [3D](https://github.com/dimforge/rapier/tree/master/examples3d). These Rust examples are note the ones you can see online though.

**Comment by aubergene** [comment]
I'm trying out Rapier since I've found issues with getting the simulation I need in Matter-js. It would be great if the demos could link directly to their source, or perhaps have a simple pure JS version with unminified source which could be a good quick starting point. I could try and work on something if this would be of interest. Thanks
