### ISSUE TITLE
Rigid bodies require manually waking when applying forces/impulses/setting velocity directly

### ISSUE THREAD

**Issue by tristanpemble** [dimforge/rapier#5]
I am having to `rb.wake_up()` whenever I apply an impulse or change velocity directly. This doesn't seem like the desired behavior

**Comment by sebcrozet** [comment]
This is actually the desired behavior, but it's open to discussion. Here are what we could do:
1. Always wake-up the bodies when applying forces, setting velocities, etc. This is an issue because there are cases where this is not desired. For example, we may want to apply forces (a radial force field for example) that may lead to a dynamic equilibrium in which case keeping all bodies awake is inefficient.
2. Never automatically wake-up the bodies and require an explicit call to `wake_up()`. This is the simplest and most flexible solution but that may appear as surprising and can lead to user code error if their forget to call `wake_up` whenever it is meaningful.
3. Add an additional boolean parameter to the functions that apply forces/modify velocity. This parameter indicates whether or not the user wants to body to wake-up. This is kind of redundant with the fact the user could call `wake_up()` explicitly, but this ensures the user is always aware that their have to make a choice whether or not the rigid-body should be woken up.

Right now 2 is the current behavior. Perhaps 3 would be better from a user-experience point of view?

**Comment by extrawurst** [comment]
@sebcrozet how are other physics libraries like box2d and physx do that?

**Comment by sebcrozet** [comment]
PhysX uses the option 3, with a default value set to `true` for the auto-wake-up parameter.
Box2d uses option 3 for force application, and always wakes up the body when setting the velocity.

So I think using option 3 everywhere is the most common option.

**Comment by tristanpemble** [comment]
maybe a 4th option to differentiate between the two via method naming. something like `add_force` vs `apply_force`. this could be even more confusing, though, if the naming is ambiguous.

**Comment by sebcrozet** [comment]
I think this 4th option will be more difficult to apply because the naming won't be easy to select and having two methods will require more maintenance.

We should settle in the option 3 (adding a boolean to each method that may end up waking things up) since it appears to be the most appreciated and common.
