### ISSUE TITLE
Overlap when a ball collider rolls off of another.

### ISSUE THREAD

**Issue by jakerr** [dimforge/rapier#76]
I adapted the bevy_rapier2d example and used a `ball` collider and notice this strange overlap as one ball rolls off of the other where it kind of falls into the other ball’s geometry for a moment:

![bevy_rapier2d_short](https://user-images.githubusercontent.com/322861/101666901-08128600-3a92-11eb-9a68-6fa33902cd95.gif)

<details><summary><b>Expand to see code for reproduction...</b></summary>
<p>

```rust
use bevy::prelude::*;
use bevy::render::pass::ClearColor;
use bevy_rapier2d::{
    physics::{RapierConfiguration, RapierPhysicsPlugin},
    rapier::{dynamics::RigidBodyBuilder, geometry::ColliderBuilder, math::Vector},
};

const PIXELS_PER_METER: f32 = 60.0;

fn main() {
    App::build()
        .add_resource(ClearColor(Color::rgb(
            0xF9 as f32 / 255.0,
            0xF9 as f32 / 255.0,
            0xFF as f32 / 255.0,
        )))
        .add_plugins(DefaultPlugins)
        .add_plugin(RapierPhysicsPlugin)
        .add_startup_system(setup_graphics.system())
        .add_startup_system(setup_physics.system())
        .run();
}

fn setup_graphics(mut commands: Commands, mut configuration: ResMut<RapierConfiguration>) {
    configuration.scale = 1.0;
    configuration.gravity = Vector::y() * -9.8 * PIXELS_PER_METER;

    commands
        .spawn(LightComponents {
            transform: Transform::from_translation(Vec3::new(1000.0, 100.0, 2000.0)),
            ..Default::default()
        })
        .spawn(Camera2dComponents {
            transform: Transform::from_translation(Vec3::new(0.0, 200.0, 0.0)),
            ..Camera2dComponents::default()
        });
}

fn ground(w: f32, h: f32, materials: &mut ResMut<Assets<ColorMaterial>>) -> SpriteComponents {
    SpriteComponents {
        sprite: Sprite {
            size: Vec2::new(w, h),
            resize_mode: SpriteResizeMode::Automatic,
        },
        material: materials.add(Color::rgb(0.3, 0.3, 0.3).into()),
        ..Default::default()
    }
}

pub fn setup_physics(
    mut commands: Commands,
    asset_server: Res<AssetServer>,
    mut materials: ResMut<Assets<ColorMaterial>>,
) {
    /*
     * Ground
     */
    let ground_size = PIXELS_PER_METER;
    let w = ground_size * 10.0;
    let h = ground_size;

    let rigid_body = RigidBodyBuilder::new_static();
    let collider = ColliderBuilder::cuboid(w / 2.0, h / 2.0);
    commands
        .spawn((rigid_body, collider))
        .with_bundle(ground(w, h, &mut materials));

    let rigid_body = RigidBodyBuilder::new_static()
        .rotation(std::f32::consts::FRAC_PI_2)
        .translation(-w / 2.0 - h / 2.0, w / 2.0 + h / 2.0);
    let collider = ColliderBuilder::cuboid(w / 2.0, h / 2.0);
    commands
        .spawn((rigid_body, collider))
        .with_bundle(ground(w, h, &mut materials));

    let rigid_body = RigidBodyBuilder::new_static()
        .rotation(std::f32::consts::FRAC_PI_2)
        .translation(w / 2.0 + h / 2.0, w / 2.0 + h / 2.0);
    let collider = ColliderBuilder::cuboid(w / 2.0, h / 2.0);
    commands
        .spawn((rigid_body, collider))
        .with_bundle(ground(w, h, &mut materials));

    let num = 1;
    let rad = ground_size / 2.0;

    let shift = rad * 2.0 + 5.0;
    let centerx = shift * (num as f32) / 2.0;
    let centery = shift / 2.0;

    // Bevy balls
    for i in 0..num {
        for j in 0usize..num * 2 {
            let x = i as f32 * shift + ((j % 5) as f32) - centerx;
            let y = j as f32 * shift + centery + 200.0;

            // Build the rigid body.
            let body = RigidBodyBuilder::new_dynamic().translation(x, y);
            let collider = ColliderBuilder::ball(rad).density(1.0);
            let texture_handle = asset_server.load("branding/icon.png");
            let sprite = SpriteComponents {
                sprite: Sprite {
                    size: Vec2::new(rad * 2.0, rad * 2.0),
                    resize_mode: SpriteResizeMode::Manual,
                },
                material: materials.add(texture_handle.into()),
                ..Default::default()
            };
            commands.spawn((body, collider)).with_bundle(sprite);
        }
    }
}
```

</p>
</details>

**Comment by sebcrozet** [comment]
Hi! Sorry for the late response.

I believe there may be a mismatch with the way sprites are rendered. Where is the local origin of sprites? If it is not at the center of the sprite, then it won't match what Rapier assumes (the center of the ball in its local-space is its local origin).

**Comment by jakerr** [comment]
I'm not at a computer where I can check right now, but I find it a bit hard to imagine this being a problem of the origins not being aligned. I'm saying this just looking at that motion where the top ball kind of hangs at about the half y position overlapping the lower one after falling a bit, and even pops back up briefly.

Another hint that this may be a bug was when I ran the same simulation with more sprites many of them seem to behave correctly while only a few exhibit this strange behavior. I reduced it to just the two before making this bug report to try to get the minimal reproduction.

**Comment by sebcrozet** [comment]
You are right. I thought that perhaps the sprite center was on the top-left corner, which would cause this kind of weird behavior because a small rotation would make them appear as if there are penetrating. But if I run your code locally, I can see that when the ball rolls on the ground, it rotates properly wrt. the sprite center.

So, yes, this is a bug. However if I try your code with my local version of Rapier (the one I'm actively working on for https://github.com/dimforge/rapier/pull/79), the bug appears to be gone. So chances are that this won't be a problem in the next release of Rapier.

By the way, I think you got your `PIXEL_PER_METER` thing reversed. If you intend to consider that 1 meter is, say, 60 pixels, then this means that when you have 1 unit in the physics world, you get 60 units in the graphics world. So you should not scale all the physics quantities by `PIXEL_PER_METER`, it is the graphics that needs to be scaled wrt. the physics. Otherwise you end up with huge objects in the physics engine (because everything is expressed in pixels) which is more prone to numerical errors.
To make this a bit easier to work with, you can set `RapierConfiguration::scale` to `PIXEL_PER_METER`. That way, the Rapier plugin will automatically multiply the rigid-body positions by `PIXEL_PER_METER` whenever it writes their position back to the Bevy `Transform`.
