### ISSUE TITLE
Octrees

### ISSUE THREAD

**Issue by iMplode-nZ** [dimforge/rapier#9]
Will Rapier support octrees? I have one project in which octrees will be very important for efficient computation of collisions and I want to know whether I should make my own engine for that or not.

**Comment by sebcrozet** [comment]
Hi! 

Could you provide details on what makes octree essential to your application? What operation would you like an octree implementation to provide for you?

An octree data structure will be added in the future, but it will not be in Rapier. It will be in the ncollide crate Rapier uses.

**Comment by iMplode-nZ** [comment]
I need efficient detection of collisions between two entities with a lot of shapes in them.

**Comment by sebcrozet** [comment]
In that case octrees are not necessarily the best choice. A bounding-volume hierarchy is also a great choice for this because they give the guarantee that each shape will be on their own tree node (whereas octrees may require shapes to be added to multiple octree nodes they intersect).
Octrees will be particularly good if you have a point cloud or a voxel grid. But for general shapes they don't have a clear advantage over bounding-volume hierarchies (which exist in ncollide as `BVT`).

**Comment by iMplode-nZ** [comment]
I do have a voxel grid. Would it be possible for me to implement a separate octree shape? If bounding volume hierachies work for most cases then it probably won't be implemented just for this case, but I would like it to be feasible.
